{{- if and ( .Values.caddyingresscontroller.rbac.create ) (eq .Values.caddyingresscontroller.watchNamespace "") }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ .Values.name }}-role
rules:
  - apiGroups:
      - ""
      - "extensions"
    resources:
      - ingresses
      - ingresses/status
      - secrets
    verbs: ["*"]
  - apiGroups:
      - ""
    resources:
      - services
      - pods
      - nodes
      - routes
      - extensions
    verbs:
      - list
      - get
      - watch
{{- end }}