{{- if and ( .Values.caddyingresscontroller.rbac.create ) (.Values.caddyingresscontroller.watchNamespace) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.name }}-role
  namespace: {{ .Values.caddyingresscontroller.watchNamespace | quote }}
rules:
  - apiGroups:
      - ""
      - "extensions"
    resources:
      - ingresses
      - ingresses/status
      - secrets
    verbs: ["*"]
  - apiGroups:
      - ""
    resources:
      - services
      - pods
      - nodes
      - routes
      - extensions
    verbs:
      - list
      - get
      - watch
{{- end }}