apiVersion: skaffold/v1beta8
kind: Config
build:
  artifacts:
  - image: caddy/ingresscontroller
deploy:
  kubectl:
    manifests:
    - hack/test/example-deployment.yaml
    - hack/test/example-ingress.yaml
    - hack/test/example-service.yaml
    - kubernetes/generated/clusterrole.yaml
    - kubernetes/generated/clusterrolebinding.yaml
    - kubernetes/generated/deployment.yaml
    - kubernetes/generated/serviceaccount.yaml
