apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: caddyingresscontroller-role
rules:
  - apiGroups:
      - ""
      - "extensions"
    resources:
      - ingresses
      - routes
      - extensions
      - ingresses/status
    verbs:
      - list
      - get
      - update
      - patch
      - watch
      - delete
  - apiGroups:
      - ""
    resources:
      - services
      - pods
      - nodes
    verbs:
      - list
      - get
      - watch
