apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: caddy-system
  labels:
    app: caddy-ingress-controller
    chart: "caddy-ingress-controller-v0.1.0"
    release: "release-name"
    heritage: "Tiller"
    version: v0.1.0

  name: caddy-ingress-controller