name: Build image with ko

permissions: write:packages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Setup ko
      uses: ko-build/setup-ko@v0.6

    - name: Build image with ko
      run: ko build ./cmd/caddy
