name: Build image with ko

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Setup ko
      uses: ko-build/setup-ko@v0.6

    - name: Build image with ko
      run: KO_DOCKER_REPO=ghcr.io/3di-clockwork/caddy-ingress-controller ko build ./cmd/caddy

    # - name: Build
    #   run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ./bin/ingress-controller ./cmd/caddy
